version: '3.8'

services:
    database:
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: swdestinydb
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '4306:3306'
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        container_name: php
        build:
            context: ./php
        ports:
            - '9000:9000'
        volumes:
            - ./server:/var/www/swdestinydb
            - ./php/parameters.yml:/var/www/swdestinydb/app/config/parameters.yml
            - ./data:/var/www/data
        depends_on:
            - database
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./server:/var/www/swdestinydb
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database